user:
  kafka:
    store: institution-user-state-store

institution:
  kafka:
    server: localhost:9092
    topic: institution
    replicas: 1
    partitions: 1
    store: institution-state-store
    retention: -1
    acks: all
    retries: 10
    requestimeout: 5000
    batch: 163850
    linger: 100
    max-in-flight: 1
    client-id: apollo-institution
    group-id: apollo-institution-group
    offset: latest

spring:
  cloud:
    function:
      definition: institutionProcessorState;userInstitutionProcessorState
    stream:
      kafka:
        streams:
          binder:
            functions:
              institutionProcessorState:
                application-id: apollo-instituion
              userInstitutionProcessorState:
                application-id: apollo-user-institution
      bindings:
        institutionProcessorState-in-0.destination: ${institution.kafka.topic}
        institutionProcessorState-out-0.destination: ${institution.kafka.store}
        userInstitutionProcessorState-in-0.destination: ${institution.kafka.topic}
        userInstitutionProcessorState-out-0.destination: ${user.kafka.store}
server:
  port: 8082

